"""
Program 2 — Pull DDI + BKG edges for new drugs
================================================
Usage:
    python3 2_pull_edges.py [--input APPENDED_7.json]

Input:  APPENDED_7.json  (or any JSON in the same schema)
        drugbank_ddi.csv / drugbank_targets.csv  (generated by parse_drugbank.py)

Outputs (all safe to copy-paste, never overwrites originals):
  out_node2id_entries.json  — paste into raw_data/Drugbank/node2id.json
  out_train_edges.txt       — paste (append) into data/drugbank/train.txt
  out_BKG_edges.txt         — paste (append) into data/drugbank/BKG_file.txt

DDI rel_id mapping:  description text → normalize → match id2rel.txt template
BKG rel_id mapping:  all DrugBank target/enzyme/transporter/carrier → CbG = 6
                     (Compound binds Gene, the correct Hetionet edge for drug-protein binding)
"""

import csv, re, json, html, argparse
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).parent

# ── input paths ───────────────────────────────────────────────────────────────
DEFAULT_INPUT   = ROOT / "APPENDED_34.json"
DDI_CSV         = ROOT / "drugbank_ddi.csv"
TGT_CSV         = ROOT / "drugbank_targets.csv"
ID2REL_TXT      = ROOT / "raw_data/Drugbank/id2rel.txt"
NODE2ID_JSON    = ROOT / "raw_data/Drugbank/node2id.json"
BKG_ENTITY_JSON = ROOT / "raw_data/Drugbank/BKG_entity2Id.json"
HETIONET_TSV    = ROOT / "raw_data/hetionet/hetionet-v1.0-nodes.tsv"

# ── output paths ─────────────────────────────────────────────────────────────
OUT_NODE2ID  = ROOT / "out_node2id_entries.json"
OUT_TRAIN    = ROOT / "out_train_edges.txt"
OUT_BKG      = ROOT / "out_BKG_edges.txt"

# BKG relation ID for all drug-protein interactions (Compound binds Gene)
CbG_REL = 6


# ═══════════════════════════════════════════════════════════════════════════════
# Helpers
# ═══════════════════════════════════════════════════════════════════════════════

def norm_desc(s: str) -> str:
    """Normalise a DDI description for template matching."""
    s = html.unescape(s)
    s = s.lower().strip().rstrip(".")
    s = re.sub(r"\s+", " ", s)
    return s


def load_templates(path: Path) -> dict[str, tuple[int, int]]:
    """
    Returns dict: norm_template → (rel_id_0indexed, subject)
    rel_id = DDI-type-N - 1  (so 'DDI type 1' → rel_id 0)
    subject = 1, 2, or 3 (3 = symmetric)
    """
    templates: dict[str, tuple[int, int]] = {}
    with open(path) as f:
        reader = csv.reader(f)
        next(reader)  # skip header
        for row in reader:
            if len(row) < 4:
                continue
            desc_raw = row[1].strip()
            subject  = int(row[2].strip())
            ddi_type = int(row[3].strip().split()[-1])   # "DDI type N" → N
            rel_id   = ddi_type - 1                       # 0-indexed
            templates[norm_desc(desc_raw)] = (rel_id, subject)
    return templates


def make_sub(desc: str, name_a: str, placeholder_a: str,
                          name_b: str, placeholder_b: str) -> str:
    """Case-insensitive replacement of name_a → placeholder_a, name_b → placeholder_b."""
    # longer name first to avoid partial replacements
    pairs = sorted([(name_a, placeholder_a), (name_b, placeholder_b)],
                   key=lambda x: -len(x[0]))
    result = desc
    for name, ph in pairs:
        result = re.sub(re.escape(name), ph, result, flags=re.IGNORECASE)
    return result


def resolve_ddi_type(desc: str, self_name: str, partner_name: str,
                     templates: dict) -> tuple[int, int, int] | None:
    """
    Returns (head_slot, tail_slot, rel_id) where slot 1=self, 2=partner
    or None if unmatched.

    head_slot=1 means self is head, head_slot=2 means partner is head.
    """
    raw = norm_desc(html.unescape(desc))

    for self_ph, partner_ph in [("#drug2", "#drug1"), ("#drug1", "#drug2")]:
        subst = norm_desc(make_sub(raw, self_name, self_ph, partner_name, partner_ph))
        if subst in templates:
            rel_id, subject = templates[subst]
            # Determine which is head based on subject column
            # subject=1 → Drug1 is head; subject=2 → Drug2 is head; subject=3 → symmetric
            if self_ph == "#drug2":
                # self=Drug2, partner=Drug1
                if subject == 1:
                    head_slot, tail_slot = 2, 1   # Drug1(partner) → Drug2(self)
                elif subject == 2:
                    head_slot, tail_slot = 1, 2   # Drug2(self) → Drug1(partner)
                else:
                    head_slot, tail_slot = 1, 2   # symmetric: self → partner
            else:
                # self=Drug1, partner=Drug2
                if subject == 1:
                    head_slot, tail_slot = 1, 2   # Drug1(self) → Drug2(partner)
                elif subject == 2:
                    head_slot, tail_slot = 2, 1   # Drug2(partner) → Drug1(self)
                else:
                    head_slot, tail_slot = 1, 2   # symmetric: self → partner
            return (head_slot, tail_slot, rel_id)

    return None


# ═══════════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", "-i", default=str(DEFAULT_INPUT),
                        help="JSON mapping file (default: APPENDED_7.json)")
    args = parser.parse_args()

    # ── load input mapping ───────────────────────────────────────────────────
    with open(args.input) as f:
        drug_map: dict = json.load(f)

    # Build lookup tables keyed by drugbank_id
    db_id_to_info: dict[str, dict] = {}       # drugbank_id → {nepal_name, knowddi_id, drugbank_name}
    db_id_to_node:  dict[str, int] = {}       # drugbank_id → node integer ID
    node_to_db_id:  dict[int, str] = {}

    for nepal_name, info in drug_map.items():
        db_id   = info["drugbank_id"]
        node_id = info["knowddi_id"]
        db_id_to_info[db_id] = {
            "nepal_name":    nepal_name,
            "knowddi_id":    node_id,
            "drugbank_name": info.get("drugbank_name", ""),
        }
        db_id_to_node[db_id]   = node_id
        node_to_db_id[node_id] = db_id

    new_db_ids = set(db_id_to_node.keys())

    # ── load existing node2id to know which partners are valid ───────────────
    with open(NODE2ID_JSON) as f:
        node2id: dict[str, int] = json.load(f)   # drugbank_name/id → node_id

    # Build DrugBank-ID → node_id from existing node2id.json
    # node2id.json keys are drugbank canonical names; values are node IDs 0-1709
    # We also need to map partner drugbank_ids (e.g. DB00001) to node IDs.
    # Strategy: re-read node2id as drugbank_name→id, plus build a reverse from MAPPED_286
    existing_name_to_node: dict[str, int] = {k.lower(): v for k, v in node2id.items()}

    # Also load MAPPED_286 so we can look up DB ID → node_id for existing drugs
    mapped_dbid_to_node: dict[str, int] = {}
    mapped_path = ROOT / "MAPPED_286.json"
    if mapped_path.exists():
        with open(mapped_path) as f:
            m286 = json.load(f)
        for nname, info in m286.items():
            mapped_dbid_to_node[info["drugbank_id"]] = info["knowddi_id"]

    # Add all new drugs to the partner lookup too (so new drugs can interact with each other)
    all_dbid_to_node: dict[str, int] = {**mapped_dbid_to_node, **db_id_to_node}

    def partner_node(partner_db_id: str) -> int | None:
        return all_dbid_to_node.get(partner_db_id)

    # ── load DDI templates ───────────────────────────────────────────────────
    print("Loading DDI templates …")
    templates = load_templates(ID2REL_TXT)
    print(f"  {len(templates)} templates loaded")

    # ── load DDI CSV into per-drug dict ─────────────────────────────────────
    print("Loading drugbank_ddi.csv …")
    ddi_by_drug: dict[str, list] = defaultdict(list)
    with open(DDI_CSV, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["drug_id"] in new_db_ids:
                ddi_by_drug[row["drug_id"]].append(row)
    total_ddi_rows = sum(len(v) for v in ddi_by_drug.values())
    print(f"  {total_ddi_rows} DDI rows found for {len(ddi_by_drug)} new drugs")

    # ── load targets CSV into per-drug dict ─────────────────────────────────
    print("Loading drugbank_targets.csv …")
    tgt_by_drug: dict[str, list] = defaultdict(list)
    with open(TGT_CSV, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["drug_id"] in new_db_ids:
                tgt_by_drug[row["drug_id"]].append(row)
    total_tgt_rows = sum(len(v) for v in tgt_by_drug.values())
    print(f"  {total_tgt_rows} target rows found for {len(tgt_by_drug)} new drugs")

    # ── build gene-symbol → entrez-id from hetionet ─────────────────────────
    print("Loading Hetionet gene nodes …")
    symbol_to_entrez: dict[str, str] = {}
    with open(HETIONET_TSV, encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            node_id_str = row["id"]     # e.g. "Gene::1"
            name        = row["name"]   # e.g. "A1BG"
            if node_id_str.startswith("Gene::"):
                entrez = node_id_str.split("::")[1]
                symbol_to_entrez[name.upper()] = entrez

    print(f"  {len(symbol_to_entrez)} gene symbols loaded")

    # ── load BKG entity map ──────────────────────────────────────────────────
    with open(BKG_ENTITY_JSON) as f:
        bkg_entity2id: dict[str, int] = json.load(f)

    # ═══════════════════════════════════════════════════════════════════════════
    # 1. node2id entries (JSON)
    # ═══════════════════════════════════════════════════════════════════════════
    node2id_out: dict[str, int] = {}
    for db_id, info in db_id_to_info.items():
        # key = drugbank canonical name (matches existing node2id.json convention)
        key = info["drugbank_name"] if info["drugbank_name"] else info["nepal_name"]
        node2id_out[key] = info["knowddi_id"]

    with open(OUT_NODE2ID, "w") as f:
        json.dump(node2id_out, f, indent=2)
    print(f"\n[1] node2id entries → {OUT_NODE2ID}  ({len(node2id_out)} drugs)")

    # ═══════════════════════════════════════════════════════════════════════════
    # 2. DDI edges (train.txt format: head_id tail_id rel_id)
    # ═══════════════════════════════════════════════════════════════════════════
    ddi_edges: list[tuple[int,int,int]] = []
    ddi_unmatched: list[str] = []
    ddi_no_partner: list[str] = []
    edge_set: set[tuple[int,int,int]] = set()  # dedup

    for db_id, rows in ddi_by_drug.items():
        info      = db_id_to_info[db_id]
        self_node = info["knowddi_id"]
        self_name = info["drugbank_name"] or info["nepal_name"]

        for row in rows:
            partner_db_id   = row["partner_id"]
            partner_name    = row["partner_name"]
            desc            = row["description"]

            pnode = partner_node(partner_db_id)
            if pnode is None:
                ddi_no_partner.append(f"{db_id}↔{partner_db_id}")
                continue

            result = resolve_ddi_type(desc, self_name, partner_name, templates)
            if result is None:
                ddi_unmatched.append(desc[:100])
                continue

            head_slot, tail_slot, rel_id = result
            head = self_node  if head_slot == 1 else pnode
            tail = pnode      if head_slot == 1 else self_node

            edge = (head, tail, rel_id)
            if edge not in edge_set:
                edge_set.add(edge)
                ddi_edges.append(edge)

    with open(OUT_TRAIN, "w") as f:
        for h, t, r in ddi_edges:
            f.write(f"{h} {t} {r}\n")

    print(f"[2] DDI edges      → {OUT_TRAIN}")
    print(f"    Written  : {len(ddi_edges)}")
    print(f"    Skipped (partner not in graph) : {len(ddi_no_partner)}")
    print(f"    Unmatched descriptions         : {len(ddi_unmatched)}")
    if ddi_unmatched:
        print("    First 5 unmatched:")
        for u in ddi_unmatched[:5]:
            print(f"      {u!r}")

    # ═══════════════════════════════════════════════════════════════════════════
    # 3. BKG edges (BKG_file.txt format: drug_id gene_id rel_id)
    # ═══════════════════════════════════════════════════════════════════════════
    bkg_edges: list[tuple[int,int,int]] = []
    bkg_no_gene: list[str] = []
    bkg_no_entrez: list[str] = []
    bkg_edge_set: set[tuple[int,int,int]] = set()

    for db_id, rows in tgt_by_drug.items():
        info      = db_id_to_info[db_id]
        drug_node = info["knowddi_id"]

        for row in rows:
            gene_sym = row["gene_name"].upper().strip()
            category = row["category"]    # target/enzyme/transporter/carrier

            if not gene_sym:
                bkg_no_gene.append(f"{db_id}:{category}")
                continue

            entrez = symbol_to_entrez.get(gene_sym)
            if entrez is None:
                bkg_no_entrez.append(gene_sym)
                continue

            gene_key = f"Gene::{entrez}"
            gene_node = bkg_entity2id.get(gene_key)
            if gene_node is None:
                bkg_no_entrez.append(f"{gene_sym}({gene_key})")
                continue

            edge = (drug_node, gene_node, CbG_REL)
            if edge not in bkg_edge_set:
                bkg_edge_set.add(edge)
                bkg_edges.append(edge)

    with open(OUT_BKG, "w") as f:
        for d, g, r in bkg_edges:
            f.write(f"{d} {g} {r}\n")

    print(f"[3] BKG edges      → {OUT_BKG}")
    print(f"    Written  : {len(bkg_edges)}")
    print(f"    No gene symbol found in Hetionet : {len(bkg_no_entrez)}")
    if bkg_no_entrez:
        print("    First 10 missing genes:", bkg_no_entrez[:10])

    print("\nDone. Copy-paste the three output files into the originals.")


if __name__ == "__main__":
    main()
